// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by scripts/gocodegen.go - DO NOT EDIT.

package ecs

import (
	"time"
)

// These fields can represent incidents related or opened on the current
// events.
// For example, a GitLab issue or a Jira event. References the Hash schema to
// sign events by a user. References the User schema to reference a user that
// changed the incident status.
type Incident struct {
	// (Automatically generated) GUID v4 that is used to reference a group of
	// events in a query
	ID string `ecs:"id"`

	// Current status of the incident
	Status string `ecs:"status"`

	// Incident update time.
	Updated time.Time `ecs:"updated"`

	// Description the user has given
	Description string `ecs:"description"`

	// URL that links to an (external) incident tracking system
	Url string `ecs:"url"`
}
